//autogenerated using zod-cli
import { z } from 'zod';

export const SubjectScheme = z.object({
	id: z.string(),
	subject: z.string(),
});

export const TeacherScheme = z.object({
	id: z.string(),
	teacher: z.string(),
});

export const GroupScheme = z.object({
	id: z.string(),
	group: z.string(),
});

export const RoomScheme = z.object({
	id: z.string(),
	room: z.string(),
});
