//autogenerated using zod-cli
import { z } from 'zod';
import { TeacherScheme } from './../../../../../../../shared/entities/schemes/types.scheme';
import { SubjectScheme } from './../../../../../../../shared/entities/schemes/types.scheme';
import { GroupScheme } from './../../../../../../../shared/entities/schemes/types.scheme';

export const JournalOptionScheme = z.object({
	teacher: TeacherScheme,
	subject: SubjectScheme,
	group: GroupScheme,
	header: z.string(),
	editable: z.boolean(),
	hasMembers: z.boolean(),
});

export const JournalCategoryScheme = z.object({
	category: z.string(),
	options: z.array(JournalOptionScheme),
});
