name: CI CD

on: [ push ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: fjogeleit/http-request-action@v1.15.4
        with:
          url: ${{ secrets.DEPLOYEER_URL }}
          method: 'POST'
          username: ${{ secrets.DEPLOYEER_USERNAME }}
          password: ${{ secrets.DEPLOYEER_PASSWORD }}
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"project": "studyum", "app": "web", "async": true}'