name: Workflow organizer

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  organize:
      name:   Organize
      runs-on: ubuntu-latest

      steps:
        - name: Organizer workflow runs
          uses: Mattraks/delete-workflow-runs@v2.0.3

          with:
            token: ${{ github.token }}
            repository: ${{ github.repository }}
            retain_days: 0
            keep_minimum_runs: 5
